### ISSUE TITLE
Lighter container

### ISSUE THREAD

**Issue by FoRTu** [EdwardChamberlain/namecheap_ddns#11]
First of all, thanks for share the container.

I use it at my unraid to instance and it works smoothly, but after I installed I saw that the Docker image file size increased more than I spect. What was my surprise when I realize that the container size was 893MB 😲:

![imagen](https://github.com/EdwardChamberlain/namecheap_ddns/assets/633679/6b64d1f4-992d-4ab3-b93e-4221289c6437)

I have been digging in your code and I could see that your container is based on the official python 3.8 image:

https://github.com/EdwardChamberlain/namecheap_ddns/blob/c306da34e17168b67b18641bbe934d60d9a52dd2/src/dockerfile#L1

Here is my question:

It would be possible to use a smaller python image? For example, Python:3.8-slim, that size is only 47.25MB instead of the one you are using now that is 360,31MB.

I don’t know the size of the dependencies of your python script, maybe is the reason of gets 893 MB.

Thanks for your time.

**Comment by EdwardChamberlain** [comment]
This is a great suggestion - thanks for making it. 

I dont see any reason that the smaller container could not be used for this as it is purely a basic python script running. I have updated and pushed a build to the development branch / tag. I have tested it on my machine and it seems to work ok.

Please feel free to try out the development branch and let me know if this has reduced the size for you?

**Comment by FoRTu** [comment]
I have been running some tests with the development branch. It works like the main one and the size have been decreased significantly:

**Size:**
![image](https://github.com/EdwardChamberlain/namecheap_ddns/assets/633679/a35281be-98d9-4287-a475-d040f5b43435)

**Running:**
![image](https://github.com/EdwardChamberlain/namecheap_ddns/assets/633679/38dabe59-e6d5-48e0-b744-95103d1c4a00)

I have not see any issue with this image change, so I could say that it could be merged to the main branch. 

Thanks for your support.

**Comment by EdwardChamberlain** [comment]
Thanks! I have merged this to main and pushed a new docker build. It should be live in a moment.

**Comment by EdwardChamberlain** [comment]
@FoRTu If you want to push this a little further the latest development image uses an even lighter base image which should drop the container size even further. It also removes a critical vulnerability in the container.

<img width="538" alt="image" src="https://github.com/EdwardChamberlain/namecheap_ddns/assets/7659338/633ee694-bf22-465c-9296-a748ffedb344">

**Comment by FoRTu** [comment]
Wow! I didn't realize that you posted this. When I have a free momment I'll try it.

Thanks!
