### ISSUE TITLE
Support for multiple hosts

### ISSUE THREAD

**Issue by tshirtnjeans** [EdwardChamberlain/namecheap_ddns#4]
Currently only accepts argument for one host.

**Comment by EdwardChamberlain** [comment]
I can see value in adding support for multiple domains/hosts/passwords. Currently, this can be achieved by spinning up multiple containers but it would be more elegant to do it all in one container. 

How would you envision passing multiple arguments to the container?

**Comment by EdwardChamberlain** [comment]
@tshirtnjeans Support for multiple hosts/domains is now supported in the development branch. You can supply as many as you like with a semi-colon `;` separated list.

**Comment by EdwardChamberlain** [comment]
Support added in the latest release.
