### ISSUE TITLE
Multiple Subdomains

### ISSUE THREAD

**Issue by ghost** [EdwardChamberlain/namecheap_ddns#9]
How can i define multiple Subdomains?

I tried 'sub1', 'sub2' but no success so far

**Comment by EdwardChamberlain** [comment]
Hi there, Apologies for the poor documentation on this one. To add multiple domains/subdomains / etc you need to provide them as a semi-colon delimited list.

For example, to add multiple sub-domains you would need to pass:

Host: `sub1;sub2;sub3`
Domain: `myDomain;myDomain;myDomain`
Password: `myPass;myPass;myPass`


Note that you **must** provide the same number of each (but repeats are fine.)

Let me know how you get on. I will update the documentation shortly.

**Comment by ThomasHineXYZ** [comment]
:open_mouth:

I came here to put this in as a feature request, since I didn't see it written anywhere. Good to know that it's a thing!

_It also might be a good thing to put notes for this in to the README file._
